github:
  user_or_org: buijennifer
channels:
  targets:
  - [jenniferbui, main]
travis:
  secure:
    BINSTAR_TOKEN: HdLjpxj19ZDsvsgWL4xPJVyTEubDbgCoQsbrAbYfy/GxnCrUkIMwnmnZHV9BIv9ENP168sxZNTL4FcUG3tjYCOzj8FaY8/qj/Nc5e3mObPuxgBruym/Ml5XCT32P7t4PZ+O/i21VM91Zf6EZWbwy8Jn3MQdC/tIWekIgJkpTmaqeX98Rw0TreyRXTJp8TUlNVhJzXm1U/k8yXkM3Bg10qrn0dR5sRscylyIb72MeVFtELopQ1jF9/co/3mv5Qv1efubRk4T1AUOsISP2eKtvTeZohD9S5TYL+l0NQyjfhmNHbQ+NA4gNZ4JJy/abRZ7XKNqDoiX/GhqBjgjZEh/nU9gn56ejz3erH0LOCzzbZIxvtwYmJBXrX8FO/hw/Co/2OhmunFoFyKCCl7BEbKtlFD2s+/ufQ7hzd2vWDOO2bL+tj7FtKIsB2ZPG9AGotRBmf/4eHAVjK83eRScPmB5QtsLPZjRC7iFiRksis036B6HKL0RClxVpo9nHOqUGUSUEhIW8xbKA1xu9/zGbqreWfurNGLblOsPCIrrCmgHcBOvGl0WztrdtKxOUUkblmEOx26uOBR0Hy1YmuqMBav+O5UDNbNckHJuf3rVbDrSeqUS6mwttbTHoW5uoeXylkY8gTNuy2ViE7ZJMKIz3B//fg1dTl8Popejf88nMeJ7WJ0k=
appveyor:
  secure:
    BINSTAR_TOKEN: yz5KKf5dQbaqyqnlq32LSt5BLNK10eqavFqOzTixaikBeNmG3G/fX870+XR0Sih/
